
#  CONTEXT BUILDER.PY – PURPOSE, ROLE, AND IMPORTANCE

# The `context_builder.py` file acts as the intelligence bridge between the raw business data and the Large Language Model (Gemini). Its primary purpose is to analyze a user's question, identify the business topic being discussed, gather the most relevant metrics from the project database, and package them into a structured context that the AI can understand and use for generating accurate responses.

# This file is necessary because Large Language Models do not have direct knowledge of our business data. Without a context builder, Gemini would only provide generic answers based on its training data and would not be able to answer questions about our revenue, customers, products, opportunities, or machine learning insights. The Context Builder solves this problem by supplying real-time business information before the question is sent to the AI.

#  The Context Builder is heavily dependent on `business_qa_engine.py`. It does not calculate business metrics on its own. Instead, it calls the functions already created inside the Business QA Engine, retrieves the required values, and organizes them into a structured format. Therefore, `business_qa_engine.py` must be working correctly before the Context Builder can function properly.

# The workflow of this file is:

# User Question → Context Builder → Business QA Engine → Database → Context Builder → AI Model

#  When a question is received, the Context Builder first determines whether the question is related to revenue, customers, geography, machine learning, opportunities, or general knowledge. After identifying the topic, it gathers the relevant metrics from the Business QA Engine and creates a structured context object containing business insights, confidence scores, and question classifications.
# Some of the most important responsibilities of this file include:

# * Identifying the business topic of a question.
#  * Classifying the type of question (analysis, metric, prediction, or general).
#  * Retrieving relevant business metrics from the Business QA Engine.
#  * Converting database and NumPy values into standard Python types.
#  * Providing confidence scores for context quality.
#  * Separating business questions from general knowledge questions.
#  * Building clean, structured context for Gemini.

#  The major functions inside this file focus on topic detection, question classification, context generation, data cleaning, and caching. These functions work together to ensure that only relevant business information is passed to the AI model.

#  For example, if a user asks "Why is revenue falling?", the Context Builder gathers revenue metrics such as total revenue, growth percentage, and average order value. If a user asks "How many customers do we have?", it retrieves customer-related metrics such as customer count, top customer segment, and average customer revenue. If a user asks a general question such as "What is machine learning?", the Context Builder recognizes that no business data is required and forwards the question as a general knowledge query.

#  The output generated by this file becomes the foundation of the final AI response. Because of this, the quality of the chatbot's answers depends heavily on the quality of the context generated here.

#  In the overall AI chatbot architecture, the Context Builder sits after the Business QA Engine and before the Prompt Builder. The Prompt Builder will use the context generated here, combine it with conversation memory and system instructions, and then send the final prompt to Gemini for response generation.

#  Project Flow:

#  Database → Business QA Engine → Context Builder → Prompt Builder → Gemini LLM → Final Response

#  In summary, `context_builder.py` is one of the most important files in the AI chatbot architecture because it transforms raw business metrics into meaningful context that enables Gemini to answer business questions accurately and intelligently.



import sys
import os

sys.path.append(
    os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__)
        )
    )
)

from Business_Agent.business_qa_engine import BusinessQAEngine
from AI_layer.Business_Agent.qa_router import QARouter


class ContextBuilder:

    def __init__(self):
        self.qa = BusinessQAEngine()
        self.router = QARouter()
        self.cache = {}

    def classify_question(self, q):
        q = q.lower()

        business_words = [
            "revenue",
            "customer",
            "customers",
            "sales",
            "product",
            "products",
            "category",
            "city",
            "state",
            "growth",
            "order",
            "orders",
            "opportunity",
            "probability",
            "segment"
        ]

        ai_words = [
            "machine learning",
            "artificial intelligence",
            "neural network",
            "deep learning",
            "llm",
            "large language model",
            "chatbot",
            "gemini",
            "openai"
        ]

        has_business = any(
            word in q
            for word in business_words
        )

        has_ai = any(
            word in q
            for word in ai_words
        )

        if has_business and has_ai:
            return "HYBRID"

        if has_business:
            return "BUSINESS"

        return "GENERAL"

    def clean_float(self, value):
        try:
            return round(float(value), 2)
        except:
            return 0.0

    def clean_int(self, value):
        try:
            return int(value)
        except:
            return 0

    def safe_call(self, func, default=None):
        try:
            return func()
        except Exception as e:
            print(
                f"Context Error: {e}"
            )
            return default




    def detect_topics(self, q):
        topics = []
        q = q.lower()

        if "customer" in q:
            topics.append("customer")

        if "revenue" in q:
            topics.append("revenue")

        if any(
            word in q
            for word in [
                "city",
                "cities",
                "state",
                "states",
                "location",
                "geographic"
            ]
        ):
            topics.append("geographic")

        if any(
            word in q
            for word in [
                "prediction",
                "forecast",
                "probability",
                "ml",
                "machine learning"
            ]
        ):
            topics.append("ml")

        return topics

      


    def get_context(self, question):

        question_type = self.classify_question(question)
        q = question.lower()

        if question_type == "GENERAL":

           return {
        "topic": "general",
        "question": question
                 }


            # Cache Check

        if question in self.cache:

             return self.cache[question]

        # ==========================================
        # GEOGRAPHIC
        # ==========================================

        if any(
            word in q
            for word in [
                "city",
                "cities",
                "state",
                "states",
                "location",
                "geographic"
            ]
        ):

            top_city = self.qa.get_top_city_by_revenue()
            top_state = self.qa.get_top_state_by_customers()
            result = {
                "topic": "geographic",
                "question_type": "metric",
                "confidence": 0.95,
                "top_city": {
                    "city": str(top_city["city"]),
                    "state": str(top_city["state"]),
                    "revenue": float(top_city["revenue"])
                },
                "top_state": {
                    "state": str(top_state["state"]),
                    "customers": int(top_state["customers"])
                }
            }
            self.cache[question] = result

            return result


        # ==========================================
        # ML
        # ==========================================

        if any(
            word in q
            for word in [
                "prediction",
                "forecast",
                "probability",
                "ml",
                "machine learning"
            ]
        ):

            result =  {

                "topic": "ml",
                "question_type": "prediction",
                 "confidence": 0.94,
                "purchase_probability":
                    float(self.qa.get_average_purchase_probability()),

                "predicted_revenue":
                    float(self.qa.get_total_predicted_revenue())
            }
            self.cache[question] = result

            return result

        # ==========================================
        # OPPORTUNITY
        # ==========================================

        if any(
            word in q
            for word in [
                "opportunity",
                "high value",
                "customer value"
            ]
        ):

            result =  {

                "topic": "opportunity",
                "question_type": "analysis",
                "confidence": 0.92,
                "high_opportunity":
                    self.qa.get_high_opportunity_customers(),

                "opportunity_score":
                    float(self.qa.get_total_opportunity_score())
            }
            self.cache[question] = result

            return result


# ==========================================
        # CUSTOMER
        # ==========================================

        if any(
            word in q
            for word in [
                "customer",
                "customers",
                "segment",
                "buyer",
                "buyers",
                "retention"
            ]
        ):

            result =  {

                "topic": "customer",
                "question_type": "analysis",
                "confidence": 0.96,
                "total_customers":
                    self.clean_int(
                     self.qa.get_customer_count()
                           ),

                "top_segment":
                    self.qa.get_top_segment(),

                "avg_customer_revenue":
                    float(self.qa.get_avg_customer_revenue())
            }
            self.cache[question] = result
            return result

        # ==========================================
        # PRODUCT
        # ==========================================

        if any(
            word in q
            for word in [
                "product",
                "products",
                "category",
                "categories",
                "item",
                "items"
            ]
        ):

            result =  {

                "topic": "product",
                "question_type": "analysis",
                "confidence": 0.92,
                "top_category":
                    self.qa.get_top_category(),

                "items_sold":
                    self.qa.get_total_items_sold()
            }
            self.cache[question] = result
            return result


        
        # ==========================================
        # REVENUE AND PREDICTED REVENUE
        # ==========================================
        if "predicted revenue" in q:

            return {
               "topic": "ml",
               "question_type": "prediction",
              "predicted_revenue":
              float(
                  self.qa.get_predicted_revenue()
              ),

              "purchase_probability":
             float(
                    self.qa.get_average_purchase_probability           ()
              )
          }
        
        elif any(
            word in q
            for word in [
                "revenue",
                "growth",
                "sales",
                "income"
            ]
        ):

            return {
                 "topic": "revenue",
                 "question_type": "analysis",
                 "confidence": 0.95,
                 "total_revenue": float(
                     self.qa.get_total_revenue()
                 ),
                 "latest_growth": float(
                     self.qa.get_latest_growth()
                 ),
                 "avg_order_value": float(
                     self.qa.get_avg_order_value()
                 )
             }

        

        

        # ==========================================
        # EXECUTIVE
        # ==========================================

        if any(
            word in q
            for word in [
                "executive",
                "overview",
                "business performance",
                "business summary",
                "company performance"
            ]
        ):

            result = {
                "topic": "executive",
                "question_type": "analysis",
                "confidence": 0.95,
                "revenue": self.safe_call(
                    self.qa.get_total_revenue,
                    0
                ),
                "customers": self.clean_int(
                    self.qa.get_total_customers()
                ),
                "orders": self.clean_int(
                    self.qa.get_total_orders()
                ),
                "avg_order_value": self.clean_float(
                    self.qa.get_avg_order_value()
                )
            }
            self.cache[question] = result
            return result
        return self.get_general_context()

    def get_business_snapshot(self):
        return {
            "revenue": self.clean_float(
                self.qa.get_total_revenue()
            ),
            "customers": self.clean_int(
                self.qa.get_total_customers()
            ),
            "orders": self.clean_int(
                self.qa.get_total_orders()
            ),
            "top_segment": self.qa.get_top_segment(),
            "top_category": self.qa.get_top_category(),
            "top_city": self.qa.get_top_city(),
            "growth": self.clean_float(
                self.qa.get_latest_growth()
            ),
            "predicted_revenue": float(
                self.qa.get_predicted_revenue()
            )
        }

    def get_general_context(self):
        return {
            "topic": "general",
            "question_type": 'general',
            "context": None,
            "confidence": 1.0,

        }